name: Run Selenium Tests
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Test with Maven
        run: mvn test --file pom.xml
      - uses: deblockt/cucumber-report-annotations-action@v1.7
      
      - name: Deploy Cucumber Reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_PAT }}
          publish_dir: ./targer/cucumber/cucumber-html-reports
